name: food_localization
description: Localization for Event Mania SALES project.

publish_to: "none" 

version: 0.0.1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/l10n/
  #   - images/a_dot_burr.jpeg#
  #- images/a_dot_ham.jpeg



